local luamods = {
	luasocket = {
		{ "socket", "mod_lua_socket" },
		{ "socket.headers", "mod_lua_headers" },
		{ "socket.http", "mod_lua_http" },
		{ "socket.url", "mod_lua_url" },
		{ "ssl", "mod_lua_ssl" },
		{ "ssl.https", "mod_lua_https" },
		{ "ltn12", "mod_lua_ltn12" },
		{ "mime", "mod_lua_mime" },
	},
	web = {
		{ "web", "mod_lua_web" },
		{ "web.server", "mod_lua_server" },
	},
	std = { "std", "std.fs", "std.ps", "std.txt", "std.tbl", "std.conv", "std.mime", "std.logger", "std.utf" },
	acme = {
		"acme",
		"acme.client",
		"acme.jws",
		"acme.orders",
		"acme.providers",
		"acme.transport",
		"acme.dns.vultr",
		"acme.http.reliw",
		"acme.store.file",
	},
	argparser = { "argparser" },
	crypto = { "crypto" },
	term = {
		"term",
		"term.widgets",
		"term.tss",
		"term.gfx",
		"term.input",
		"term.input.history",
		"term.input.prompt",
		"term.input.completion",
	},
	testimony = { "testimony" },
	dns = { "dns.resolver", "dns.parser", "dns.dig" },
	llm = {
		"llm",
		"llm.llamacpp",
		"llm.anthropic",
		"llm.oaic",
		"llm.templates",
		"llm.tools",
		"llm.tools.read_file",
		"llm.tools.write_file",
		"llm.tools.edit_file",
		"llm.tools.bash",
		"llm.tools.web_search",
		"llm.tools.fetch_webpage",
		"llm.pricing",
	},
	redis = { "redis" },
	reliw = {
		"reliw",
		"reliw.api",
		"reliw.auth",
		"reliw.handle",
		"reliw.metrics",
		"reliw.store",
		"reliw.proxy",
		"reliw.templates",
	},
	botls = { "botls", "botls.config", "botls.manager", "botls.orders", "botls.providers", "botls.scheduler" },
	shell = {
		"shell",
		"shell.theme",
		"shell.store",
		"shell.utils",
		"shell.utils.pager",
		"shell.utils.pipeline",
		"shell.jobs",
		"shell.builtins",
		"shell.mode.shell",
		"shell.mode.shell.prompt",
		"shell.mode.lua",
		"shell.mode.lua.prompt",
		"shell.completion.shell",
		"shell.completion.lua",
		"shell.completion.source.bin",
		"shell.completion.source.builtins",
		"shell.completion.source.cmds",
		"shell.completion.source.env",
		"shell.completion.source.fs",
		"shell.completion.source.lua_keywords",
		"shell.completion.source.lua_symbols",
	},
	vault = { "vault" },
	zxscr = { "zxscr" },
	zx = { "zx", "zx.keyboard", "zx.screen" },
	agent = {
		"agent.config",
		"agent.conversation",
		"agent.system_prompt",
		"agent.tools",
		"agent.theme",
		"agent.stream",
		"agent.mode.agent",
		"agent.mode.agent.prompt",
	},
	markdown = {
		"markdown",
		"markdown.parser",
		"markdown.state",
		"markdown.events",
		"markdown.inline",
		"markdown.buffer",
		"markdown.renderer",
		"markdown.renderer.theme",
		"markdown.renderer.table_layout",
		"markdown.renderer.static",
		"markdown.renderer.streaming",
		"markdown.renderer.html",
	},
}

local c_libs = {
	luasocket = {
		{ "socket.core", "luaopen_socket_core" },
		{ "socket.unix", "luaopen_socket_unix" },
		{ "socket.serial", "luaopen_socket_serial" },
		{ "mime.core", "luaopen_mime_core" },
		{ "ssl.context", "luaopen_ssl_context" },
		{ "ssl.core", "luaopen_ssl_core" },
	},
	cjson = {
		{ "cjson", "luaopen_cjson" },
		{ "cjson.safe", "luaopen_cjson_safe" },
	},
	std = {
		{ "std.core", "luaopen_deviant_core" },
	},
	inotify = {
		{ "inotify", "luaopen_inotify" },
	},
	crypto = {
		{ "crypto.core", "luaopen_crypto_core" },
	},
	term = {
		{ "term.core", "luaopen_term_core" },
	},
	wireguard = {
		{ "wireguard", "luaopen_wireguard" },
	},
	zx = {
		{ "zx.core", "luaopen_zx_core" },
		{ "zx.audio", "luaopen_zx_audio" },
	},
}

return { c_libs = c_libs, luamods = luamods }
