return {
	binary = "lilush",
	luamods = {
		"luasocket",
		"web",
		"std",
		"crypto",
		"term",
		"redis",
		"shell",
		"vault",
		"llm",
		"dns",
		"argparser",
		"acme",
		"testimony",
		"zxscr",
		"agent",
		"markdown",
	},
	c_libs = {
		"cjson",
		"inotify",
		"luasocket",
		"std",
		"crypto",
		"term",
		"wireguard",
	},
	start_code = {
		EXEC_BUILTIN = "lilush/exec_builtin.lua",
		START_SHELL = "lilush/start_shell.lua",
		RUN_SHELL_CMD = "lilush/run_shell_cmd.lua",
		PRELOAD_INIT = "lilush/preload_init.lua",
	},
	custom_main = "lilush/main.c",
}
